export const SET_DRAWER_VISIBILITY = "SET_DRAWER_VISIBILITY";
export const GET_DRAWER_VISIBILITY = "GET_DRAWER_VISIBILITY";

export const TOGGLE_THEME = "TOGGLE_THEME";
export const GET_THEME = "GET_THEME";
